- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"


- name: Install Prerequisites
  yum:
    name:
     - httpd
     - epel-release
     - "{{zabbix_repo}}"
    update_cache: yes
    
- name: enable php72
  shell: yum-config-manager --enable "{{php_version}}" 


- name: Install Prerequisites
  yum:
    name:
     - zabbix-agent
    update_cache: yes

- name: enable rhel-server
  shell: yum-config-manager --enable rhel-server-rhscl-7-rpms


- name: enable frontend
  lineinfile:
    path: /etc/yum.repos.d/zabbix.repo 
    regexp: '^Zabbix server'
    line: 'Centos-1'


- name: enable frontend
  lineinfile:
    path: /etc/yum.repos.d/zabbix.repo 
    regexp: '^127.0.0.1'
    line: '59.203.183.136'  
    
    
- name: Start zabbix-agent
  service:
    name: zabbix-agent
    state: restarted
    enabled: yes

- name: Start Apache
  service:
    name: httpd
    state: restarted
    enabled: yes


