- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"


- name: Install Prerequisites
  yum:
    name:
     - httpd
     - epel-release
     - "{{zabbix_repo}}"
    update_cache: yes
  when: ansible_os_family == 'RedHat'

- name: Install Prerequisites
  package:
    name:
     - apache2
     - "{{zabbix_repo}}"
    update_cache: yes
  when: ansible_os_family == 'Debian'
    
- name: Install zabbix-agent
  yum:
    name:
     - zabbix-agent
    update_cache: yes
  when: ansible_os_family == 'RedHat'

- name: Install zabbix-agent
  yum:
    name:
     - zabbix-agent
    update_cache: yes
  when: ansible_os_family == 'Debian'
  

- name: creating zabbix_agentd.conf
  template:
    src: "zabbix_agentd.conf"
    dest: "/etc/zabbix/zabbix_agentd.conf"

    
- name: Start zabbix-agent
  service:
    name: zabbix-agent
    state: restarted
    enabled: yes

- name: Start Apache centos
  service:
    name: httpd
    state: restarted
    enabled: yes
  when: ansible_os_family == 'RedHat'

- name: Start Apache for ubuntu
  service:
    name: httpd
    state: restarted
    enabled: yes
  when: ansible_os_family == 'Debian'


