- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"


- name: Install Prerequisites
  yum:
    name:
     - httpd
     - epel-release
     - "{{zabbix_repo}}"
    update_cache: yes
    
- name: enable php72
  shell: yum-config-manager --enable "{{php_version}}" 


- name: Install zabbix-agent
  yum:
    name:
     - zabbix-agent
    update_cache: yes

- name: creating zabbix_agentd.conf
  template:
    src: "zabbix_agentd.conf"
    dest: "/etc/zabbix/zabbix_agentd.conf"

    
- name: Start zabbix-agent
  service:
    name: zabbix-agent
    state: restarted
    enabled: yes

- name: Start Apache
  service:
    name: httpd
    state: restarted
    enabled: yes


