- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"


- name: Install Prerequisites
  yum:
    name:
     - httpd
     - epel-release
     - "{{zabbix_repo}}"
    update_cache: yes
  when: ansible_os_family == 'RedHat'


- name: Download zabbix-release_5.0-1+focal_all.deb
  get_url:
    url: https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb
    dest: /tmp/
    mode: '600'
  when: ansible_os_family == 'Debian'

- name: download zabbix repo ubuntu
  command: dpkg -i zabbix-release_5.0-1+focal_all.deb
  args:
    chdir: /tmp/
  when: ansible_os_family == 'Debian'

- name: Install Prerequisites
  apt:
    name:
     - apache2
     - zabbix-agent
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install zabbix-agent
  yum:
    name:
     - zabbix-agent
    update_cache: yes
  when: ansible_os_family == 'RedHat'


- name: creating zabbix_agentd.conf
  template:
    src: "zabbix_agentd.conf"
    dest: "/etc/zabbix/zabbix_agentd.conf"

    
- name: Start zabbix-agent
  service:
    name: zabbix-agent
    state: restarted
    enabled: yes

- name: Start Apache centos
  service:
    name: httpd
    state: restarted
    enabled: yes
  when: ansible_os_family == 'RedHat'

- name: Start Apache for ubuntu
  service:
    name: apache2
    state: restarted
    enabled: yes
  when: ansible_os_family == 'Debian'




